# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ";;espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ";;date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Print the current DateTime formatted by ISO8601
  - trigger: ";;now"
    replace: "{{iso8601}}"
    vars:
      - name: iso8601
        type: date
        params:
          format: "%+"

  # Print the output of a shell command
  - trigger: ";;shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Foldable syntax in Markdown
  - trigger: ";;details"
    replace: |
      <details><summary>$|$</summary><div>
      :)
      </div></details>

  - trigger: ";;evi"
    replace: "テスト🦐デンス"

  - trigger: ";;xss"
    replace: "<img src=x onerror=alert();>"

  - trigger: ";;hr"
    replace: "--------------------"

