[tools]
actionlint = "1.7.11"
ghalint = "latest"
node = "lts"
"npm:git-cz" = "latest"
"npm:pnpm" = "latest"
pinact = "latest"
uv = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []

