icons:
  when: never

blocks:
  - permission
  - size
  - user
  - date
  - name

# strftime format -> https://strftime.org/
date: "+%d %b %y %X"

size: short

symlink-arrow: ->

sorting:
  dir-grouping: first