"$schema" = "https://starship.rs/config-schema.json"

format = """
$directory$git_branch$git_state$git_status
$character"""

[directory]
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[▶](bold green)"
error_symbol   = "[▶](bold red)"

[cmd_duration]
disabled = true

[package]
disabled = true

[os]
disabled = false

[git_status]
staged = "•"
untracked = "+"
deleted = "x"
ahead = "▲${count}"
behind = "▼${count}"
diverged = "▲${ahead_count} ▼${behind_count}"