[cmd_duration]
disabled = true

[package]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[>](bold green)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

# [hostname]
# ssh_only = false
# format =  ": [$hostname](bold red) "
# trim_at = ".companyname.com"
# disabled = false

